export const DEFAULT_STATE = {
  FieldID: 0,
  FieldName: "",
  inputtype: "",
  PlaceHolder_Label: "Both",
  IsMandatory: true,
  IsAutoFill: false,
  IsCalender: false,
  RowIDX: 180,
  ColIDX: 200,
  default_RowIDX: 180,
  default_ColIDX: 200,
  id: "",
  FieldHeight: 70,
  dependentSectiononFieldValues: [
    {
      MainFieldID: 0,
      MainFieldValue: "",
      SectionID:0,
      SectionName: '',
      SectionVisibility: false,
    },
  ],
  FieldWidth: 230,
  uiitemsvalues: [
    {
      UIValue: "",
    },
  ],
  sectionsLists: [],
  IsClickEventAvailable: false,
  IsForMail: false,
  ClickEventURL: null,
  DefaultVisibility: true,
  IsToolTip: true,
  ToolTiptext: "",
  ButtonOperation: null,
  IsButtonforFileUpload: false,
  ButtonEventURL: null,
  uibuttonfields: null,
  colspan: "0",
  isAlign: {
    value: "LEFT",
    label: "LEFT",
  },
  isHeader: false,
  uIstyleItems: {
    bgcolorcode: "",
    forecolorcode: "",
    FontSize: "",
    FontName: "",
    IsBold: true,
    IsItalic: false,
    IsUnderLine: false,
    Height: "",
    Width: "",
    LeftMgn: "",
    RightMgn: "",
    TopMgn: "",
    BottomMgn: "",
  },
  dependentCol: false,
  staticfieldvalue: [
    {
      Value: "",
      IsActive: false,
      Seqno: 1,
    },
  ],
  IsActive: true,
  AutoIDDisplay: false,
  IsCheckinDependentTable: false,
  isDrag: false,
  updated: true,
  Buttoncolorcode: "",
  dependentFields: [
    {
      MainFieldID: 0,
      MainColValue: "",
      ModuleID: 0,
      SubcolID: {
        value: "",
        label: "",
      },
      IsActive: false,
      FieldVisible: false,
    },
  ],
};
